development:
  adapter: postgresql
  encoding: unicode
  database: carma_dev
  host: localhost
  pool: 5
  username: ronakabhattrz
  password: ronakabhattrz

production:
  adapter: postgresql
  encoding: unicode
  database: carma
  pool: 5
  timeout: 5000
  username: ronakabhattrz
  password: ronakabhattrz